DELETE
FROM STEEL;

DELETE
FROM USERS;

DELETE
FROM ROLES;

DELETE
FROM USERROLES;

DELETE
FROM KNIFETYPE;

DELETE
FROM APPLICATION;


INSERT INTO KNIFETYPE (KNIFETYPEID, KNIFETYPE, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 'Axe', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 'Pocket Knife', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (2, 'Chef Knife', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO USERS (USERID, USERNAME, PASSWORD, USEREMAIL, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 'admin', '$2y$12$UnEZMYkcrg.FgGhN7XApr.KM11Ow..DmT/RmQ1uz2nlcIOmqsqoJ6', 'admin@admin.admin', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 'jacob', '$2y$12$UnEZMYkcrg.FgGhN7XApr.KM11Ow..DmT/RmQ1uz2nlcIOmqsqoJ6', 'j@o.co', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO ROLES(ROLEID, NAME, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 'ADMIN', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 'USER', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO USERROLES(ROLEID, USERID, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 0, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO APPLICATION (APPLICATIONID, APPLICATION, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 'Plastics', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 'Waffles', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO STEEL (STEELID, APPLICATIONID, KNIFETYPEID, STEELNAME, MANUFACTURER, STEELDESCRIPTION, ROCKWELLHARDNESS, SHARPENING, EDGERETENTION, STAINLESS, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE)
VALUES (0, 0, 0, 'M390', 'Bohler-Uddeholm', 'Popular', '60-62', '8', '10', '8', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
       (1, 1, 1, 'K390', 'Bohler-Uddeholm', 'Super D2 type steel', '62-64', '7', '10', '2', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);


alter sequence hibernate_sequence restart with 15;
